
SELECT BFI_ID         AS BANK_CD, 
       TRIM(BFI_DSC)    AS BANK_DSC,
       PKCS_00_00_DMV.FN_00_BFI_TP_DSC(BFI_DM) AS BANK_TYPE_DSC,
       NIBSS_ID
FROM CR_00_BFI
WHERE DMD_DM = '00_BFI_TP'
AND   IUS_YN = '1'
ORDER BY DSP_ORD, DM_DSC
WITH READ ONLY;
/
